
DELETE FROM tblMstCountry

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DBCC CHECKIDENT ('tblMstCountry', RESEED, 1);  
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('AFGHANISTAN (‫افغانستان‬‎)','AF','93')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('ALBANIA (SHQIPËRI)','AL','355')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('ALGERIA (‫الجزائر‬‎)','DZ','213')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('AMERICAN SAMOA','AS','1684')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('ANDORRA','AD','376')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('ANGOLA','AO','244')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('ANGUILLA','AI','1264')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('ANTIGUA AND BARBUDA','AG','1268')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('ARGENTINA','AR','54')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('ARMENIA (ՀԱՅԱՍՏԱՆ)','AM','374')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('ARUBA','AW','297')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('AUSTRALIA','AU','61')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('AUSTRIA (ÖSTERREICH)','AT','43')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('AZERBAIJAN (AZƏRBAYCAN)','AZ','994')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('BAHAMAS','BS','1242')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('BAHRAIN (‫البحرين‬‎)','BH','973')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('BANGLADESH (বাংলাদেশ)','BD','880')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('BARBADOS','BB','1246')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('BELARUS (БЕЛАРУСЬ)','BY','375')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('BELGIUM (BELGIË)','BE','32')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('BELIZE','BZ','501')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('BENIN (BÉNIN)','BJ','229')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('BERMUDA','BM','1441')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('BHUTAN (འབྲུག)','BT','975')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('BOLIVIA','BO','591')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('BOSNIA AND HERZEGOVINA (БОСНА И ХЕРЦЕГОВИНА)','BA','387')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('BOTSWANA','BW','267')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('BRAZIL (BRASIL)','BR','55')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('BRITISH INDIAN OCEAN TERRITORY','IO','246')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('BRITISH VIRGIN ISLANDS','VG','1284')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('BRUNEI','BN','673')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('BULGARIA (БЪЛГАРИЯ)','BG','359')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('BURKINA FASO','BF','226')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('BURUNDI (UBURUNDI)','BI','257')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('CAMBODIA (កម្ពុជា)','KH','855')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('CAMEROON (CAMEROUN)','CM','237')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('CANADA','CA','1')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('CAPE VERDE (KABU VERDI)','CV','238')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('CARIBBEAN NETHERLANDS','BQ','599')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('CAYMAN ISLANDS','KY','1345')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('CENTRAL AFRICAN REPUBLIC','CF','236')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('CHAD (TCHAD)','TD','235')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('CHILE','CL','56')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('CHINA (中国)','CN','86')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('CHRISTMAS ISLAND','CX','61')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('COCOS (KEELING) ISLANDS','CC','61')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('COLOMBIA','CO','57')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('COMOROS (‫جزر القمر‬‎)','KM','269')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('CONGO (DRC) (JAMHURI YA KIDEMOKRASIA YA KONGO)','CD','243')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('CONGO (REPUBLIC) (CONGO-BRAZZAVILLE)','CG','242')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('COOK ISLANDS','CK','682')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('COSTA RICA','CR','506')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('CÔTE D’IVOIRE','CI','225')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('CROATIA (HRVATSKA)','HR','385')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('CUBA','CU','53')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('CURAÇAO','CW','599')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('CYPRUS (ΚΎΠΡΟΣ)','CY','357')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('CZECH REPUBLIC (ČESKÁ REPUBLIKA)','CZ','420')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('DENMARK (DANMARK)','DK','45')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('DJIBOUTI','DJ','253')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('DOMINICA','DM','1767')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('DOMINICAN REPUBLIC (REPÚBLICA DOMINICANA)','DO','1')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('ECUADOR','EC','593')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('EGYPT (‫مصر‬‎)','EG','20')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('EL SALVADOR','SV','503')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('EQUATORIAL GUINEA (GUINEA ECUATORIAL)','GQ','240')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('ERITREA','ER','291')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('ESTONIA (EESTI)','EE','372')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('ETHIOPIA','ET','251')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('FALKLAND ISLANDS (ISLAS MALVINAS)','FK','500')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('FAROE ISLANDS (FØROYAR)','FO','298')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('FIJI','FJ','679')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('FINLAND (SUOMI)','FI','358')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('FRANCE','FR','33')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('FRENCH GUIANA (GUYANE FRANÇAISE)','GF','594')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('FRENCH POLYNESIA (POLYNÉSIE FRANÇAISE)','PF','689')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('GABON','GA','241')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('GAMBIA','GM','220')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('GEORGIA (საქართველო)','GE','995')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('GERMANY (DEUTSCHLAND)','DE','49')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('GHANA (GAANA)','GH','233')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('GIBRALTAR','GI','350')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('GREECE (ΕΛΛΆΔΑ)','GR','30')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('GREENLAND (KALAALLIT NUNAAT)','GL','299')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('GRENADA','GD','1473')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('GUADELOUPE','GP','590')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('GUAM','GU','1671')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('GUATEMALA','GT','502')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('GUERNSEY','GG','44')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('GUINEA (GUINÉE)','GN','224')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('GUINEA-BISSAU (GUINÉ BISSAU)','GW','245')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('GUYANA','GY','592')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('HAITI','HT','509')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('HONDURAS','HN','504')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('HONG KONG (香港)','HK','852')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('HUNGARY (MAGYARORSZÁG)','HU','36')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('ICELAND (ÍSLAND)','IS','354')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('INDIA (भारत)','IN','91')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('INDONESIA','ID','62')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('IRAN (‫ایران‬‎)','IR','98')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('IRAQ (‫العراق‬‎)','IQ','964')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('IRELAND','IE','353')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('ISLE OF MAN','IM','44')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('ISRAEL (‫ישראל‬‎)','IL','972')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('ITALY (ITALIA)','IT','39')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('JAMAICA','JM','1876')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('JAPAN (日本)','JP','81')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('JERSEY','JE','44')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('JORDAN (‫الأردن‬‎)','JO','962')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('KAZAKHSTAN (КАЗАХСТАН)','KZ','7')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('KENYA','KE','254')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('KIRIBATI','KI','686')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('KOSOVO','XK','383')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('KUWAIT (‫الكويت‬‎)','KW','965')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('KYRGYZSTAN (КЫРГЫЗСТАН)','KG','996')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('LAOS (ລາວ)','LA','856')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('LATVIA (LATVIJA)','LV','371')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('LEBANON (‫لبنان‬‎)','LB','961')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('LESOTHO','LS','266')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('LIBERIA','LR','231')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('LIBYA (‫ليبيا‬‎)','LY','218')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('LIECHTENSTEIN','LI','423')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('LITHUANIA (LIETUVA)','LT','370')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('LUXEMBOURG','LU','352')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('MACAU (澳門)','MO','853')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('MACEDONIA (FYROM) (МАКЕДОНИЈА)','MK','389')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('MADAGASCAR (MADAGASIKARA)','MG','261')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('MALAWI','MW','265')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('MALAYSIA','MY','60')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('MALDIVES','MV','960')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('MALI','ML','223')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('MALTA','MT','356')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('MARSHALL ISLANDS','MH','692')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('MARTINIQUE','MQ','596')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('MAURITANIA (‫موريتانيا‬‎)','MR','222')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('MAURITIUS (MORIS)','MU','230')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('MAYOTTE','YT','262')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('MEXICO (MÉXICO)','MX','52')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('MICRONESIA','FM','691')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('MOLDOVA (REPUBLICA MOLDOVA)','MD','373')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('MONACO','MC','377')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('MONGOLIA (МОНГОЛ)','MN','976')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('MONTENEGRO (CRNA GORA)','ME','382')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('MONTSERRAT','MS','1664')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('MOROCCO (‫المغرب‬‎)','MA','212')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('MOZAMBIQUE (MOÇAMBIQUE)','MZ','258')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('MYANMAR (BURMA) (မြန်မာ)','MM','95')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('NAMIBIA (NAMIBIË)','NA','264')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('NAURU','NR','674')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('NEPAL (नेपाल)','NP','977')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('NETHERLANDS (NEDERLAND)','NL','31')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('NEW CALEDONIA (NOUVELLE-CALÉDONIE)','NC','687')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('NEW ZEALAND','NZ','64')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('NICARAGUA','NI','505')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('NIGER (NIJAR)','NE','227')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('NIGERIA','NG','234')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('NIUE','NU','683')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('NORFOLK ISLAND','NF','672')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('NORTH KOREA (조선 민주주의 인민 공화국)','KP','850')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('NORTHERN MARIANA ISLANDS','MP','1670')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('NORWAY (NORGE)','NO','47')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('OMAN (‫عُمان‬‎)','OM','968')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('PAKISTAN (‫پاکستان‬‎)','PK','92')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('PALAU','PW','680')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('PALESTINE (‫فلسطين‬‎)','PS','970')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('PANAMA (PANAMÁ)','PA','507')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('PAPUA NEW GUINEA','PG','675')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('PARAGUAY','PY','595')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('PERU (PERÚ)','PE','51')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('PHILIPPINES','PH','63')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('POLAND (POLSKA)','PL','48')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('PORTUGAL','PT','351')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('PUERTO RICO','PR','1')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('QATAR (‫قطر‬‎)','QA','974')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('RÉUNION (LA RÉUNION)','RE','262')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('ROMANIA (ROMÂNIA)','RO','40')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('RUSSIA (РОССИЯ)','RU','7')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('RWANDA','RW','250')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SAINT BARTHÉLEMY (SAINT-BARTHÉLEMY)','BL','590')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SAINT HELENA','SH','290')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SAINT KITTS AND NEVIS','KN','1869')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SAINT LUCIA','LC','1758')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SAINT MARTIN (SAINT-MARTIN (PARTIE FRANÇAISE))','MF','590')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SAINT PIERRE AND MIQUELON','PM','508')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SAINT VINCENT AND THE GRENADINES','VC','1784')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SAMOA','WS','685')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SAN MARINO','SM','378')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SÃO TOMÉ AND PRÍNCIPE (SÃO TOMÉ E PRÍNCIPE)','ST','239')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SAUDI ARABIA (‫المملكة العربية السعودية‬‎)','SA','966')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SENEGAL (SÉNÉGAL)','SN','221')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SERBIA (СРБИЈА)','RS','381')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SEYCHELLES','SC','248')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SIERRA LEONE','SL','232')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SINGAPORE','SG','65')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SINT MAARTEN','SX','1721')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SLOVAKIA (SLOVENSKO)','SK','421')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SLOVENIA (SLOVENIJA)','SI','386')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SOLOMON ISLANDS','SB','677')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SOMALIA (SOOMAALIYA)','SO','252')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SOUTH AFRICA','ZA','27')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SOUTH KOREA (대한민국)','KR','82')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SOUTH SUDAN (‫جنوب السودان‬‎)','SS','211')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SPAIN (ESPAÑA)','ES','34')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SRI LANKA (ශ්‍රී ලංකාව)','LK','94')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SUDAN (‫السودان‬‎)','SD','249')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SURINAME','SR','597')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SVALBARD AND JAN MAYEN','SJ','47')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SWAZILAND','SZ','268')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SWEDEN (SVERIGE)','SE','46')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SWITZERLAND (SCHWEIZ)','CH','41')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('SYRIA (‫سوريا‬‎)','SY','963')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('TAIWAN (台灣)','TW','886')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('TAJIKISTAN','TJ','992')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('TANZANIA','TZ','255')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('THAILAND (ไทย)','TH','66')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('TIMOR-LESTE','TL','670')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('TOGO','TG','228')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('TOKELAU','TK','690')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('TONGA','TO','676')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('TRINIDAD AND TOBAGO','TT','1868')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('TUNISIA (‫تونس‬‎)','TN','216')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('TURKEY (TÜRKIYE)','TR','90')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('TURKMENISTAN','TM','993')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('TURKS AND CAICOS ISLANDS','TC','1649')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('TUVALU','TV','688')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('U.S. VIRGIN ISLANDS','VI','1340')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('UGANDA','UG','256')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('UKRAINE (УКРАЇНА)','UA','380')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('UNITED ARAB EMIRATES (‫الإمارات العربية المتحدة‬‎)','AE','971')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('UNITED KINGDOM','GB','44')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('UNITED STATES','US','1')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('URUGUAY','UY','598')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('UZBEKISTAN (OʻZBEKISTON)','UZ','998')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('VANUATU','VU','678')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('VATICAN CITY (CITTÀ DEL VATICANO)','VA','39')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('VENEZUELA','VE','58')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('VIETNAM (VIỆT NAM)','VN','84')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('WALLIS AND FUTUNA','WF','681')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('WESTERN SAHARA (‫الصحراء الغربية‬‎)','EH','212')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('YEMEN (‫اليمن‬‎)','YE','967')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('ZAMBIA','ZM','260')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('ZIMBABWE','ZW','263')
INSERT INTO tblMstCountry (CountryName, CountryCode, CountryISDCode) VALUES('ÅLAND ISLANDS','AX','358')